### ISSUE TITLE
Batch: follow up issues from initial release

### ISSUE THREAD

**Issue by gr2m** [project-forms/project-forms.github.io#4]
Follow up to #2 

### Tasks

- [ ] Issue drafts
- [ ] Add fields from issue forms
- [ ] Set issue meta data like labels, assignees, and milestone
- [ ] Filter what project fields are shown based query parameter
- [ ] Editing issues
- [ ] Submitting issues to projects without write access
- [ ] Submitting issues to repositories without read access
- [ ] Displaying past issues submitted with the form
- [ ] Build steps and other optimizations
